### ISSUE TITLE
2022.1.7 could not load type from assemble 2022.1.3

### ISSUE THREAD

**Issue by russgreen** [Nice3point/RevitExtensions#4]
Trying out the extensions but fell at the first.

Adding the nuget with Version="$(RevitVersion).*" and 2022.1.7 is in use but when I try .GetElements() or .GetInstances() the following runtime error occurs:

Could not load type 'Nice3point.Revit.Extensions.CollectorExtensions' from assembly 'Nice3point.Revit.Extensions, Version=2022.1.3.0, Culture=neutral, PublicKeyToken=null'.

**Comment by Nice3point** [comment]
Perhaps you have a plugin installed with an old version of the library, where this class is not present

**Comment by Nice3point** [comment]
the error states that Revit downloaded version 2022.1.3 instead of the new one. Possible solutions: go to the Revit add-ons folder %appdata%\Autodesk\Revit\Addins\ and replace this library in other plugins

**Comment by russgreen** [comment]
yes. sorry.   RevitLookup using an older version.
